# Generated by Django 4.2.3 on 2023-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categotyType',
            new_name='categoryType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='postAuthor',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=128),
        ),
    ]
